import type { GlobeMonitorEvent, MonitorEventCategory, MonitorImpact } from "./types";

export const MONITOR_FILTERS: MonitorEventCategory[] = [
  "Conflict Zones",
  "Diplomacy",
  "Economics",
  "Energy",
  "Trade",
  "Regulation",
];

export const IMPACT_RANK: Record<MonitorImpact, number> = {
  Watch: 1,
  Elevated: 2,
  High: 3,
  Critical: 4,
};

export const GLOBE_MONITOR_EVENTS: GlobeMonitorEvent[] = [
  {
    id: "red-sea-shipping-risk",
    title: "Red Sea Shipping Risk",
    region: "Middle East",
    country: "Egypt",
    lat: 26.8,
    lng: 30.8,
    category: "Conflict Zones",
    impact: "High",
    headline: "Shipping disruption risk remains elevated near Red Sea routes.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T10:00:00Z",
    priority: 1,
    label: "Egypt",
    summary: "Insurance and rerouting pressure remain the dominant transmission channels for energy and freight markets.",
    watchlist: ["Suez throughput", "War-risk premium", "Brent freight basis"],
    labelOffset: { x: 24, y: -10 },
    fallbackPosition: { x: 74, y: 40 },
  },
  {
    id: "usa-policy-cycle",
    title: "US Policy Cycle",
    region: "North America",
    country: "USA",
    lat: 38.9,
    lng: -77,
    category: "Regulation",
    impact: "High",
    headline: "Washington regulatory signals keep strategic sectors on alert.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T09:40:00Z",
    priority: 1,
    label: "USA",
    summary: "Policy risk is concentrated around technology controls, industrial incentives, and capital-market scrutiny.",
    watchlist: ["Export controls", "Industrial policy", "Treasury sanctions"],
    labelOffset: { x: -26, y: -18 },
    fallbackPosition: { x: 29, y: 43 },
  },
  {
    id: "canada-critical-minerals",
    title: "Critical Minerals Corridor",
    region: "North America",
    country: "Canada",
    lat: 56.1,
    lng: -106.3,
    category: "Energy",
    impact: "Elevated",
    headline: "North American mineral supply chains draw fresh investment attention.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T08:55:00Z",
    priority: 2,
    label: "Canada",
    summary: "Battery metals, grid infrastructure, and defense supply chains remain the core exposure set.",
    watchlist: ["Lithium permits", "Grid capex", "Defense procurement"],
    labelOffset: { x: -36, y: -20 },
    fallbackPosition: { x: 30, y: 29 },
  },
  {
    id: "mexico-nearshoring",
    title: "Nearshoring Capacity Watch",
    region: "North America",
    country: "Mexico",
    lat: 23.6,
    lng: -102.5,
    category: "Trade",
    impact: "Elevated",
    headline: "Industrial nearshoring flows keep northern corridor logistics tight.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T08:30:00Z",
    priority: 2,
    label: "Mexico",
    summary: "Border capacity and power reliability are the near-term gating factors for new manufacturing commitments.",
    watchlist: ["Border dwell time", "Power availability", "Auto supply chains"],
    labelOffset: { x: -42, y: 14 },
    fallbackPosition: { x: 25, y: 55 },
  },
  {
    id: "peru-copper-output",
    title: "Copper Output Watch",
    region: "Latin America",
    country: "Peru",
    lat: -9.2,
    lng: -75,
    category: "Economics",
    impact: "Watch",
    headline: "Copper production monitoring rises as industrial metals hedge demand firms.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T07:55:00Z",
    priority: 3,
    label: "Peru",
    summary: "A modest disruption would still matter because refined copper inventories remain thin.",
    watchlist: ["Mine output", "Port movement", "Copper curve"],
    labelOffset: { x: -20, y: 28 },
    fallbackPosition: { x: 38, y: 78 },
  },
  {
    id: "china-demand-pulse",
    title: "China Demand Pulse",
    region: "East Asia",
    country: "China",
    lat: 35.9,
    lng: 104.2,
    category: "Economics",
    impact: "High",
    headline: "Manufacturing and credit data remain central to global risk appetite.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T09:25:00Z",
    priority: 1,
    label: "China",
    summary: "The market is watching whether policy support converts into real demand for commodities and equipment.",
    watchlist: ["PMI", "Credit impulse", "Iron ore"],
    labelOffset: { x: -24, y: -48 },
    fallbackPosition: { x: 55, y: 34 },
  },
  {
    id: "japan-yen-intervention",
    title: "Yen Intervention Watch",
    region: "East Asia",
    country: "Japan",
    lat: 36.2,
    lng: 138.3,
    category: "Economics",
    impact: "Elevated",
    headline: "FX desks track official language as yen volatility persists.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T09:10:00Z",
    priority: 2,
    label: "Japan",
    summary: "Rates, imported inflation, and exporters are the main channels into global equity risk.",
    watchlist: ["USD/JPY", "JGB yields", "Exporter hedges"],
    labelOffset: { x: 72, y: -64 },
    fallbackPosition: { x: 64, y: 36 },
  },
  {
    id: "korea-memory-cycle",
    title: "Memory Cycle Signal",
    region: "East Asia",
    country: "Korea",
    lat: 36.5,
    lng: 127.9,
    category: "Trade",
    impact: "Elevated",
    headline: "Memory pricing and AI server demand keep Korea in focus.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T08:48:00Z",
    priority: 2,
    label: "Korea",
    summary: "The key signal is whether high-bandwidth memory demand keeps lifting the broader export complex.",
    watchlist: ["HBM pricing", "KRW", "Semiconductor exports"],
    labelOffset: { x: 26, y: -108 },
    fallbackPosition: { x: 61, y: 32 },
  },
  {
    id: "india-energy-imports",
    title: "Energy Import Exposure",
    region: "South Asia",
    country: "India",
    lat: 21.1,
    lng: 78.9,
    category: "Energy",
    impact: "High",
    headline: "India remains sensitive to shipping premiums and crude volatility.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T08:20:00Z",
    priority: 1,
    label: "India",
    summary: "Energy import costs, rupee sensitivity, and public-sector refiners are the main monitor lines.",
    watchlist: ["Brent", "USD/INR", "Refiner margins"],
    labelOffset: { x: -54, y: 30 },
    fallbackPosition: { x: 55, y: 51 },
  },
  {
    id: "sri-lanka-port-flows",
    title: "Indian Ocean Port Flow",
    region: "South Asia",
    country: "Sri Lanka",
    lat: 7.9,
    lng: 80.7,
    category: "Trade",
    impact: "Watch",
    headline: "Transshipment activity remains a useful read on Indian Ocean trade flows.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T07:30:00Z",
    priority: 3,
    label: "Sri Lanka",
    summary: "Port flow changes can surface early pressure in regional container routes.",
    watchlist: ["Colombo TEU", "Bunker pricing", "Route dwell"],
    labelOffset: { x: 32, y: 34 },
    fallbackPosition: { x: 60, y: 58 },
  },
  {
    id: "france-eu-diplomacy",
    title: "EU Diplomatic Track",
    region: "Europe",
    country: "France",
    lat: 46.2,
    lng: 2.2,
    category: "Diplomacy",
    impact: "Elevated",
    headline: "European policy coordination remains active across security and trade files.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T09:05:00Z",
    priority: 2,
    label: "France",
    summary: "The signal is concentrated in defense procurement, fiscal posture, and EU trade negotiations.",
    watchlist: ["EU Council", "Defense names", "OAT spreads"],
    labelOffset: { x: 108, y: -42 },
    fallbackPosition: { x: 68, y: 33 },
  },
  {
    id: "spain-energy-terminal",
    title: "LNG Terminal Watch",
    region: "Europe",
    country: "Spain",
    lat: 40.4,
    lng: -3.7,
    category: "Energy",
    impact: "Watch",
    headline: "Iberian LNG infrastructure stays relevant to European gas flexibility.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T07:15:00Z",
    priority: 3,
    label: "Spain",
    summary: "Terminal utilization and gas spreads remain useful stress indicators for the EU energy complex.",
    watchlist: ["LNG send-out", "TTF", "Power margins"],
    labelOffset: { x: -30, y: 10 },
    fallbackPosition: { x: 67, y: 43 },
  },
  {
    id: "hong-kong-capital-flow",
    title: "Capital Flow Monitor",
    region: "East Asia",
    country: "Hong Kong",
    lat: 22.3,
    lng: 114.2,
    category: "Regulation",
    impact: "Elevated",
    headline: "Hong Kong liquidity and listings remain a read-through for China risk.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T08:10:00Z",
    priority: 2,
    label: "Hong Kong",
    summary: "Capital-market activity provides a faster signal than slower macro releases.",
    watchlist: ["IPO queue", "HIBOR", "Southbound flows"],
    labelOffset: { x: 44, y: -2 },
    fallbackPosition: { x: 58, y: 44 },
  },
  {
    id: "philippines-maritime-pressure",
    title: "Maritime Pressure Watch",
    region: "Southeast Asia",
    country: "Philippines",
    lat: 12.9,
    lng: 121.8,
    category: "Conflict Zones",
    impact: "High",
    headline: "Maritime incidents keep security risk elevated in regional waters.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T09:00:00Z",
    priority: 1,
    label: "Philippines",
    summary: "Shipping, fisheries, and defense posture are the active transmission points.",
    watchlist: ["Patrol activity", "Insurance tone", "Defense procurement"],
    labelOffset: { x: 94, y: 36 },
    fallbackPosition: { x: 62, y: 52 },
  },
  {
    id: "malaysia-malacca-flow",
    title: "Malacca Flow Monitor",
    region: "Southeast Asia",
    country: "Malaysia",
    lat: 4.2,
    lng: 102,
    category: "Trade",
    impact: "High",
    headline: "Malacca corridor flow remains a core global logistics risk monitor.",
    sourceUrl: "#",
    updatedAt: "2026-04-27T08:38:00Z",
    priority: 1,
    label: "Malaysia",
    summary: "Energy, container freight, and electronics supply chains all converge through this corridor.",
    watchlist: ["Vessel density", "Bunker fuel", "Electronics freight"],
    labelOffset: { x: 18, y: 88 },
    fallbackPosition: { x: 58, y: 60 },
  },
];
