from app.models import (
    Chokepoint,
    Coordinates,
    Country,
    FxPulse,
    GlobalPulse,
    MarketIndex,
    MarketMovement,
    MarketPoint,
    PulseAlert,
    Sector,
    SectorArc,
    TensionBreakdown,
    TradePartner,
)


def series(*values: float) -> list[MarketPoint]:
    labels = ["1D", "1W", "1M", "3M", "6M", "1Y"]
    return [MarketPoint(label=label, value=value) for label, value in zip(labels, values)]


def breakdown(structural: float, sentiment: float, live_trigger: float) -> TensionBreakdown:
    return TensionBreakdown(
        structural=structural,
        sentiment=sentiment,
        live_trigger=live_trigger,
        last_structural_update="March 2026",
        last_sentiment_update="April 13, 2026",
    )


COUNTRIES: dict[str, Country] = {
    "USA": Country(
        iso3="USA",
        iso_numeric="840",
        name="United States",
        flag="https://flagcdn.com/us.svg",
        capital="Washington, D.C.",
        coordinates=Coordinates(lat=38.9, lng=-77.0),
        gdp_usd_bn=28780,
        population_mn=341.8,
        gdp_growth_pct=2.5,
        gdp_per_capita_usd=83400,
        gini=41.4,
        tension_score=4.6,
        tension_label="Developing",
        tension_breakdown=breakdown(3.9, 5.4, 4.8),
        groups=["G7", "G20", "NATO", "AUKUS", "QUAD", "MSP"],
        industry_criticality=["AI accelerators", "Semiconductor design", "USD reserve system"],
        trade_partners=[
            TradePartner(iso3="CHN", name="China", flow="export", share=7.5, thesis="Consumer demand and industrial inputs"),
            TradePartner(iso3="CAN", name="Canada", flow="export", share=17.5, thesis="Energy, autos, and integrated supply chains"),
            TradePartner(iso3="MEX", name="Mexico", flow="export", share=16.0, thesis="Nearshore manufacturing corridor"),
            TradePartner(iso3="CHN", name="China", flow="import", share=14.0, thesis="Electronics and machinery concentration"),
            TradePartner(iso3="MEX", name="Mexico", flow="import", share=15.5, thesis="Autos and factory inputs"),
            TradePartner(iso3="DEU", name="Germany", flow="import", share=5.0, thesis="Precision machinery and autos"),
        ],
        market_index=MarketIndex(
            symbol="SPX",
            name="S&P 500",
            currency="USD",
            change_24h=-0.6,
            series=series(100, 101.5, 99.8, 104.2, 108.5, 116.0),
        ),
        fx=FxPulse(pair="DXY", rate=105.2, volatility_24h=0.7, trigger="Treasury yields firm after tariff guidance"),
        contrarian_insight="Policy noise is amber, but reshoring capex keeps industrial earnings less fragile than the headlines imply.",
    ),
    "IND": Country(
        iso3="IND",
        iso_numeric="356",
        name="India",
        flag="https://flagcdn.com/in.svg",
        capital="New Delhi",
        coordinates=Coordinates(lat=28.6, lng=77.2),
        gdp_usd_bn=3940,
        population_mn=1428.6,
        gdp_growth_pct=6.8,
        gdp_per_capita_usd=2730,
        gini=35.7,
        tension_score=4.9,
        tension_label="Developing",
        tension_breakdown=breakdown(4.4, 5.2, 5.1),
        groups=["G20", "BRICS+", "QUAD", "SCO", "MSP"],
        industry_criticality=["Generic pharma", "Digital public infrastructure", "Electronics assembly"],
        trade_partners=[
            TradePartner(iso3="USA", name="United States", flow="export", share=17.8, thesis="Services and pharma demand"),
            TradePartner(iso3="ARE", name="United Arab Emirates", flow="export", share=7.4, thesis="Energy finance and re-export hub"),
            TradePartner(iso3="CHN", name="China", flow="export", share=3.6, thesis="Specialty chemicals and materials"),
            TradePartner(iso3="CHN", name="China", flow="import", share=15.4, thesis="Electronics and active pharmaceutical ingredients"),
            TradePartner(iso3="RUS", name="Russia", flow="import", share=8.8, thesis="Discount crude supply"),
            TradePartner(iso3="SAU", name="Saudi Arabia", flow="import", share=6.9, thesis="Crude oil and petrochemicals"),
        ],
        market_index=MarketIndex(
            symbol="NIFTY",
            name="Nifty 50",
            currency="INR",
            change_24h=0.4,
            series=series(100, 100.8, 102.6, 106.0, 109.4, 118.2),
        ),
        fx=FxPulse(pair="USD/INR", rate=83.45, volatility_24h=0.5, trigger="Crude volatility offset by equity inflows"),
        contrarian_insight="If crude cools while border noise stays amber, India quietly gains margin relief before the index reprices it.",
    ),
    "CHN": Country(
        iso3="CHN",
        iso_numeric="156",
        name="China",
        flag="https://flagcdn.com/cn.svg",
        capital="Beijing",
        coordinates=Coordinates(lat=39.9, lng=116.4),
        gdp_usd_bn=18530,
        population_mn=1409.7,
        gdp_growth_pct=4.7,
        gdp_per_capita_usd=13150,
        gini=38.2,
        tension_score=6.6,
        tension_label="Developing",
        tension_breakdown=breakdown(5.8, 7.0, 6.9),
        groups=["G20", "BRICS+", "SCO", "RCEP"],
        industry_criticality=["Rare earth processing", "Battery supply chain", "Solar manufacturing"],
        trade_partners=[
            TradePartner(iso3="USA", name="United States", flow="export", share=14.8, thesis="Consumer electronics and machinery"),
            TradePartner(iso3="JPN", name="Japan", flow="export", share=4.8, thesis="Industrial components"),
            TradePartner(iso3="KOR", name="South Korea", flow="export", share=4.5, thesis="Electronics ecosystem"),
            TradePartner(iso3="TWN", name="Taiwan", flow="import", share=7.1, thesis="Advanced semiconductor inputs"),
            TradePartner(iso3="KOR", name="South Korea", flow="import", share=6.2, thesis="Memory and display components"),
            TradePartner(iso3="BRA", name="Brazil", flow="import", share=4.9, thesis="Iron ore and soy complex"),
        ],
        market_index=MarketIndex(
            symbol="000300",
            name="CSI 300",
            currency="CNY",
            change_24h=-1.2,
            series=series(100, 98.8, 97.4, 95.5, 93.8, 91.0),
        ),
        fx=FxPulse(pair="USD/CNY", rate=7.24, volatility_24h=0.8, trigger="Export controls keep yuan risk premium elevated"),
        contrarian_insight="The market discounts property drag, but battery exports still give Beijing leverage in any green-tech negotiation.",
    ),
    "TWN": Country(
        iso3="TWN",
        iso_numeric="158",
        name="Taiwan",
        flag="https://flagcdn.com/tw.svg",
        capital="Taipei",
        coordinates=Coordinates(lat=25.0, lng=121.5),
        gdp_usd_bn=803,
        population_mn=23.4,
        gdp_growth_pct=3.2,
        gdp_per_capita_usd=34400,
        gini=34.1,
        tension_score=8.4,
        tension_label="High Risk",
        tension_breakdown=breakdown(7.2, 8.8, 9.1),
        groups=["APEC", "Critical: Semiconductors"],
        industry_criticality=["60% global foundry share", "90% advanced chip concentration", "TSMC system node"],
        trade_partners=[
            TradePartner(iso3="CHN", name="China", flow="export", share=25.2, thesis="Chip demand and assembly channel"),
            TradePartner(iso3="USA", name="United States", flow="export", share=15.7, thesis="AI server and fabless design demand"),
            TradePartner(iso3="JPN", name="Japan", flow="export", share=6.9, thesis="Materials and industrial electronics"),
            TradePartner(iso3="JPN", name="Japan", flow="import", share=15.0, thesis="Specialty chemicals and tools"),
            TradePartner(iso3="USA", name="United States", flow="import", share=10.9, thesis="Design IP and equipment"),
            TradePartner(iso3="NLD", name="Netherlands", flow="import", share=5.2, thesis="Lithography equipment dependency"),
        ],
        market_index=MarketIndex(
            symbol="TAIEX",
            name="Taiwan Weighted",
            currency="TWD",
            change_24h=-1.8,
            series=series(100, 99.2, 101.0, 109.5, 114.7, 131.5),
        ),
        fx=FxPulse(pair="USD/TWD", rate=32.15, volatility_24h=1.1, trigger="Airspace alerts raised semiconductor risk hedge"),
        contrarian_insight="The risk premium is real, but AI capex makes every Taiwan dip a referendum on global compute scarcity.",
    ),
    "JPN": Country(
        iso3="JPN",
        iso_numeric="392",
        name="Japan",
        flag="https://flagcdn.com/jp.svg",
        capital="Tokyo",
        coordinates=Coordinates(lat=35.7, lng=139.7),
        gdp_usd_bn=4210,
        population_mn=123.3,
        gdp_growth_pct=0.9,
        gdp_per_capita_usd=33800,
        gini=32.9,
        tension_score=3.8,
        tension_label="Developing",
        tension_breakdown=breakdown(3.0, 4.2, 4.4),
        groups=["G7", "G20", "QUAD", "RCEP", "CPTPP", "MSP"],
        industry_criticality=["Semiconductor chemicals", "Robotics", "Automotive precision"],
        trade_partners=[
            TradePartner(iso3="USA", name="United States", flow="export", share=19.8, thesis="Autos and equipment demand"),
            TradePartner(iso3="CHN", name="China", flow="export", share=17.6, thesis="Machinery and components"),
            TradePartner(iso3="KOR", name="South Korea", flow="export", share=7.1, thesis="Materials and components"),
            TradePartner(iso3="CHN", name="China", flow="import", share=23.5, thesis="Electronics and manufactured goods"),
            TradePartner(iso3="USA", name="United States", flow="import", share=10.3, thesis="Energy and aircraft"),
            TradePartner(iso3="SAU", name="Saudi Arabia", flow="import", share=6.6, thesis="Crude oil exposure"),
        ],
        market_index=MarketIndex(
            symbol="N225",
            name="Nikkei 225",
            currency="JPY",
            change_24h=-0.3,
            series=series(100, 102.0, 104.4, 111.0, 119.5, 127.2),
        ),
        fx=FxPulse(pair="USD/JPY", rate=154.7, volatility_24h=0.9, trigger="Yield spread pressure persists"),
        contrarian_insight="A weak yen stresses households, but it still amplifies exporter earnings during global capex cycles.",
    ),
    "KOR": Country(
        iso3="KOR",
        iso_numeric="410",
        name="South Korea",
        flag="https://flagcdn.com/kr.svg",
        capital="Seoul",
        coordinates=Coordinates(lat=37.6, lng=126.9),
        gdp_usd_bn=1760,
        population_mn=51.7,
        gdp_growth_pct=2.2,
        gdp_per_capita_usd=34100,
        gini=33.3,
        tension_score=5.7,
        tension_label="Developing",
        tension_breakdown=breakdown(5.1, 5.8, 6.2),
        groups=["G20", "APEC", "MSP"],
        industry_criticality=["Memory semiconductors", "Shipbuilding", "Battery cells"],
        trade_partners=[
            TradePartner(iso3="CHN", name="China", flow="export", share=19.7, thesis="Intermediate electronics"),
            TradePartner(iso3="USA", name="United States", flow="export", share=18.3, thesis="Autos, chips, and batteries"),
            TradePartner(iso3="JPN", name="Japan", flow="export", share=4.7, thesis="Materials and machinery"),
            TradePartner(iso3="CHN", name="China", flow="import", share=21.6, thesis="Components and industrial inputs"),
            TradePartner(iso3="USA", name="United States", flow="import", share=11.2, thesis="Energy and equipment"),
            TradePartner(iso3="JPN", name="Japan", flow="import", share=7.5, thesis="Precision inputs"),
        ],
        market_index=MarketIndex(
            symbol="KOSPI",
            name="KOSPI",
            currency="KRW",
            change_24h=0.2,
            series=series(100, 101.2, 102.0, 104.1, 106.8, 112.3),
        ),
        fx=FxPulse(pair="USD/KRW", rate=1378.0, volatility_24h=0.8, trigger="Chip exports offset regional defense premium"),
        contrarian_insight="Defense risk is visible, but memory pricing can turn faster than geopolitical screens imply.",
    ),
    "NLD": Country(
        iso3="NLD",
        iso_numeric="528",
        name="Netherlands",
        flag="https://flagcdn.com/nl.svg",
        capital="Amsterdam",
        coordinates=Coordinates(lat=52.4, lng=4.9),
        gdp_usd_bn=1118,
        population_mn=17.9,
        gdp_growth_pct=1.1,
        gdp_per_capita_usd=62400,
        gini=26.0,
        tension_score=2.9,
        tension_label="Stable",
        tension_breakdown=breakdown(2.3, 3.0, 3.4),
        groups=["EU", "NATO", "G20 Guest", "MSP"],
        industry_criticality=["EUV lithography", "Port of Rotterdam", "Agri-tech exports"],
        trade_partners=[
            TradePartner(iso3="DEU", name="Germany", flow="export", share=24.0, thesis="Industrial re-export corridor"),
            TradePartner(iso3="BEL", name="Belgium", flow="export", share=11.5, thesis="Benelux logistics"),
            TradePartner(iso3="USA", name="United States", flow="export", share=6.0, thesis="Equipment and chemicals"),
            TradePartner(iso3="DEU", name="Germany", flow="import", share=16.7, thesis="Machinery and autos"),
            TradePartner(iso3="CHN", name="China", flow="import", share=10.2, thesis="Consumer and industrial goods"),
            TradePartner(iso3="USA", name="United States", flow="import", share=8.1, thesis="Energy and technology"),
        ],
        market_index=MarketIndex(
            symbol="AEX",
            name="AEX",
            currency="EUR",
            change_24h=0.1,
            series=series(100, 100.3, 101.7, 103.5, 105.8, 110.9),
        ),
        fx=FxPulse(pair="EUR/USD", rate=1.08, volatility_24h=0.4, trigger="ECB path steadies after gas storage update"),
        contrarian_insight="The country looks calm, but one export-license headline from ASML can move the global chip chain.",
    ),
    "DEU": Country(
        iso3="DEU",
        iso_numeric="276",
        name="Germany",
        flag="https://flagcdn.com/de.svg",
        capital="Berlin",
        coordinates=Coordinates(lat=52.5, lng=13.4),
        gdp_usd_bn=4590,
        population_mn=84.7,
        gdp_growth_pct=0.3,
        gdp_per_capita_usd=54200,
        gini=31.7,
        tension_score=4.2,
        tension_label="Developing",
        tension_breakdown=breakdown(3.8, 4.1, 4.9),
        groups=["G7", "G20", "EU", "NATO", "MSP"],
        industry_criticality=["Automotive exports", "Industrial machinery", "European manufacturing base"],
        trade_partners=[
            TradePartner(iso3="USA", name="United States", flow="export", share=10.2, thesis="Autos and machinery"),
            TradePartner(iso3="FRA", name="France", flow="export", share=7.6, thesis="EU industrial demand"),
            TradePartner(iso3="CHN", name="China", flow="export", share=6.2, thesis="Autos and factory equipment"),
            TradePartner(iso3="CHN", name="China", flow="import", share=11.5, thesis="Electronics and industrial inputs"),
            TradePartner(iso3="NLD", name="Netherlands", flow="import", share=8.4, thesis="Energy and port logistics"),
            TradePartner(iso3="USA", name="United States", flow="import", share=7.0, thesis="Technology and LNG"),
        ],
        market_index=MarketIndex(
            symbol="DAX",
            name="DAX",
            currency="EUR",
            change_24h=-0.4,
            series=series(100, 99.8, 101.1, 105.6, 108.0, 114.8),
        ),
        fx=FxPulse(pair="EUR/USD", rate=1.08, volatility_24h=0.4, trigger="Industrial PMIs remain uneven"),
        contrarian_insight="Weak macro hides operating leverage: any energy relief flows straight into German industrial margins.",
    ),
    "SAU": Country(
        iso3="SAU",
        iso_numeric="682",
        name="Saudi Arabia",
        flag="https://flagcdn.com/sa.svg",
        capital="Riyadh",
        coordinates=Coordinates(lat=24.7, lng=46.7),
        gdp_usd_bn=1100,
        population_mn=36.9,
        gdp_growth_pct=1.8,
        gdp_per_capita_usd=29800,
        gini=45.9,
        tension_score=5.4,
        tension_label="Developing",
        tension_breakdown=breakdown(4.7, 5.5, 6.1),
        groups=["G20", "BRICS+", "OPEC", "OPEC+", "GCC"],
        industry_criticality=["Swing oil capacity", "Petrochemicals", "Red Sea logistics"],
        trade_partners=[
            TradePartner(iso3="CHN", name="China", flow="export", share=18.4, thesis="Crude oil demand"),
            TradePartner(iso3="IND", name="India", flow="export", share=10.2, thesis="Crude and petrochemicals"),
            TradePartner(iso3="JPN", name="Japan", flow="export", share=9.1, thesis="Energy security channel"),
            TradePartner(iso3="CHN", name="China", flow="import", share=20.9, thesis="Machinery and consumer goods"),
            TradePartner(iso3="USA", name="United States", flow="import", share=9.3, thesis="Aircraft and defense systems"),
            TradePartner(iso3="ARE", name="United Arab Emirates", flow="import", share=6.4, thesis="Regional re-export flows"),
        ],
        market_index=MarketIndex(
            symbol="TASI",
            name="Tadawul All Share",
            currency="SAR",
            change_24h=0.7,
            series=series(100, 99.5, 100.9, 102.0, 103.4, 108.1),
        ),
        fx=FxPulse(pair="USD/SAR", rate=3.75, volatility_24h=0.1, trigger="Peg steady as crude risk premium rises"),
        contrarian_insight="If Hormuz risk rises, Saudi equities can lag oil first, then rerate as spare capacity becomes strategic leverage.",
    ),
    "ARE": Country(
        iso3="ARE",
        iso_numeric="784",
        name="United Arab Emirates",
        flag="https://flagcdn.com/ae.svg",
        capital="Abu Dhabi",
        coordinates=Coordinates(lat=24.5, lng=54.4),
        gdp_usd_bn=536,
        population_mn=10.2,
        gdp_growth_pct=3.7,
        gdp_per_capita_usd=52900,
        gini=26.0,
        tension_score=3.6,
        tension_label="Developing",
        tension_breakdown=breakdown(3.1, 3.6, 4.2),
        groups=["BRICS+", "OPEC", "OPEC+", "GCC"],
        industry_criticality=["Re-export hub", "Sovereign wealth", "AI infrastructure capital"],
        trade_partners=[
            TradePartner(iso3="IND", name="India", flow="export", share=13.5, thesis="Gold, energy, and re-export corridor"),
            TradePartner(iso3="CHN", name="China", flow="export", share=7.8, thesis="Re-export and energy flows"),
            TradePartner(iso3="JPN", name="Japan", flow="export", share=6.4, thesis="Crude and LNG"),
            TradePartner(iso3="CHN", name="China", flow="import", share=18.1, thesis="Electronics and consumer goods"),
            TradePartner(iso3="IND", name="India", flow="import", share=7.9, thesis="Jewelry, food, and services linkages"),
            TradePartner(iso3="USA", name="United States", flow="import", share=6.3, thesis="Aircraft and technology"),
        ],
        market_index=MarketIndex(
            symbol="DFMGI",
            name="Dubai Financial Market",
            currency="AED",
            change_24h=0.5,
            series=series(100, 100.7, 102.5, 106.2, 109.1, 118.9),
        ),
        fx=FxPulse(pair="USD/AED", rate=3.67, volatility_24h=0.1, trigger="Peg steady despite regional hedging"),
        contrarian_insight="Regional risk can drive capital into UAE assets when investors need Gulf exposure without frontier liquidity risk.",
    ),
    "RUS": Country(
        iso3="RUS",
        iso_numeric="643",
        name="Russia",
        flag="https://flagcdn.com/ru.svg",
        capital="Moscow",
        coordinates=Coordinates(lat=55.8, lng=37.6),
        gdp_usd_bn=2240,
        population_mn=144.2,
        gdp_growth_pct=3.1,
        gdp_per_capita_usd=15500,
        gini=36.0,
        tension_score=8.1,
        tension_label="High Risk",
        tension_breakdown=breakdown(7.4, 8.0, 8.8),
        groups=["BRICS+", "G20", "SCO", "OPEC+"],
        industry_criticality=["Pipeline gas", "Uranium enrichment", "Wheat exports"],
        trade_partners=[
            TradePartner(iso3="CHN", name="China", flow="export", share=31.0, thesis="Energy and commodities"),
            TradePartner(iso3="IND", name="India", flow="export", share=14.2, thesis="Discount crude"),
            TradePartner(iso3="TUR", name="Turkey", flow="export", share=7.0, thesis="Energy and transit trade"),
            TradePartner(iso3="CHN", name="China", flow="import", share=36.5, thesis="Machinery and sanctioned substitutes"),
            TradePartner(iso3="IND", name="India", flow="import", share=4.3, thesis="Pharma and machinery"),
            TradePartner(iso3="BRA", name="Brazil", flow="import", share=3.0, thesis="Food and industrial inputs"),
        ],
        market_index=MarketIndex(
            symbol="IMOEX",
            name="MOEX Russia",
            currency="RUB",
            change_24h=-1.5,
            series=series(100, 97.8, 99.0, 101.8, 96.3, 89.5),
        ),
        fx=FxPulse(pair="USD/RUB", rate=93.8, volatility_24h=1.9, trigger="Sanctions premium and energy payment friction"),
        contrarian_insight="Sanction risk is obvious, but uranium and fertilizer exposure keep Russia embedded in hidden supply chains.",
    ),
    "BRA": Country(
        iso3="BRA",
        iso_numeric="076",
        name="Brazil",
        flag="https://flagcdn.com/br.svg",
        capital="Brasilia",
        coordinates=Coordinates(lat=-15.8, lng=-47.9),
        gdp_usd_bn=2170,
        population_mn=203.1,
        gdp_growth_pct=2.1,
        gdp_per_capita_usd=10680,
        gini=52.0,
        tension_score=3.1,
        tension_label="Stable",
        tension_breakdown=breakdown(3.0, 3.2, 3.1),
        groups=["G20", "BRICS+", "MERCOSUR"],
        industry_criticality=["Iron ore", "Soy exports", "Biofuels"],
        trade_partners=[
            TradePartner(iso3="CHN", name="China", flow="export", share=30.7, thesis="Soy, iron ore, and crude"),
            TradePartner(iso3="USA", name="United States", flow="export", share=10.9, thesis="Aircraft and commodities"),
            TradePartner(iso3="ARG", name="Argentina", flow="export", share=4.8, thesis="Regional industrial demand"),
            TradePartner(iso3="CHN", name="China", flow="import", share=22.1, thesis="Manufactured goods and equipment"),
            TradePartner(iso3="USA", name="United States", flow="import", share=16.0, thesis="Fuels and machinery"),
            TradePartner(iso3="DEU", name="Germany", flow="import", share=5.1, thesis="Chemicals and machinery"),
        ],
        market_index=MarketIndex(
            symbol="IBOV",
            name="Bovespa",
            currency="BRL",
            change_24h=0.9,
            series=series(100, 101.4, 103.0, 100.5, 106.2, 111.6),
        ),
        fx=FxPulse(pair="USD/BRL", rate=5.11, volatility_24h=1.0, trigger="Iron ore bid offsets fiscal noise"),
        contrarian_insight="If China stabilizes, Brazil screens as a quiet convex play on both food security and industrial metals.",
    ),
}


GLOBAL_PULSE = GlobalPulse(
    alerts=[
        PulseAlert(
            id="taiwan-strait-sorties",
            severity="High Risk",
            region="Taiwan Strait",
            headline="Air and maritime activity raises hedge demand across chip-linked markets",
            impact="TSMC suppliers and Korea memory names trade with a wider risk premium.",
            age_minutes=42,
        ),
        PulseAlert(
            id="hormuz-insurance",
            severity="Developing",
            region="Persian Gulf",
            headline="Tanker insurance premia widen as Hormuz monitoring intensifies",
            impact="Brent-linked inflation hedges outperform broad energy equities.",
            age_minutes=57,
        ),
        PulseAlert(
            id="export-controls",
            severity="Developing",
            region="US, EU, China",
            headline="New dual-use export reviews slow advanced equipment clearances",
            impact="Lithography and AI accelerator supply chains face timing risk.",
            age_minutes=86,
        ),
    ],
    daily_briefs=[
        "Semiconductor risk is clustering around chokepoints, not just around fabs.",
        "Energy markets are pricing route security before they price physical shortage.",
        "Critical minerals policy is shifting from efficiency to redundancy.",
    ],
    last_structural_update="March 2026",
    last_sentiment_update="April 13, 2026",
)


MARKET_PULSE = [
    MarketMovement(
        id="taiwan-weighted",
        instrument="TAIEX",
        move_pct=-1.8,
        region="Taiwan",
        trigger="Airspace alerts revived chip continuity hedges.",
    ),
    MarketMovement(
        id="brent",
        instrument="Brent crude",
        move_pct=2.2,
        region="Middle East",
        trigger="Hormuz insurance costs rose.",
    ),
    MarketMovement(
        id="usd-krw",
        instrument="USD/KRW",
        move_pct=0.8,
        region="Korea",
        trigger="Defense premium offset export strength.",
    ),
]


CHOKEPOINTS = {
    "malacca": Chokepoint(
        id="malacca",
        name="Strait of Malacca",
        coordinates=Coordinates(lat=1.4, lng=103.8),
        watch="Controls a critical share of East Asia semiconductor and mineral flows.",
    ),
    "hormuz": Chokepoint(
        id="hormuz",
        name="Strait of Hormuz",
        coordinates=Coordinates(lat=26.6, lng=56.3),
        watch="A red signal here reprices crude, LNG, and CPI risk globally.",
    ),
    "suez": Chokepoint(
        id="suez",
        name="Suez Canal",
        coordinates=Coordinates(lat=30.6, lng=32.3),
        watch="Links Asian manufacturing with European consumption routes.",
    ),
}


SECTORS: dict[str, Sector] = {
    "semiconductors": Sector(
        id="semiconductors",
        name="Semiconductors",
        color="#00ffff",
        market_value="$600B direct",
        systemic_multiplier="$3.5T+ industrial dependency",
        sensitivity=9.8,
        power_nodes=["TWN", "NLD", "USA", "JPN", "KOR"],
        consumption_nodes=["CHN", "DEU", "IND"],
        arcs=[
            SectorArc(source="NLD", target="TWN", intensity=0.95, waypoint="suez"),
            SectorArc(source="USA", target="TWN", intensity=0.85),
            SectorArc(source="JPN", target="TWN", intensity=0.78),
            SectorArc(source="KOR", target="CHN", intensity=0.72, waypoint="malacca"),
            SectorArc(source="TWN", target="USA", intensity=0.92),
            SectorArc(source="TWN", target="DEU", intensity=0.66, waypoint="suez"),
            SectorArc(source="TWN", target="IND", intensity=0.58, waypoint="malacca"),
        ],
        chokepoints=[CHOKEPOINTS["malacca"], CHOKEPOINTS["suez"]],
        brief="Chips are the new oil: a narrow set of nodes controls the compute layer under AI, autos, defense, and consumer electronics.",
        alpha="Watch the Netherlands. An ASML export license delay can move the whole technology roadmap before Taiwan risk changes.",
        equity_proxy="SOXX / TSM",
    ),
    "hydrocarbons": Sector(
        id="hydrocarbons",
        name="Hydrocarbons",
        color="#ffb000",
        market_value="$2.1T direct",
        systemic_multiplier="Global CPI transmission",
        sensitivity=8.5,
        power_nodes=["SAU", "ARE", "USA", "RUS"],
        consumption_nodes=["CHN", "IND", "DEU", "JPN"],
        arcs=[
            SectorArc(source="SAU", target="IND", intensity=0.9, waypoint="hormuz"),
            SectorArc(source="SAU", target="CHN", intensity=0.95, waypoint="hormuz"),
            SectorArc(source="ARE", target="JPN", intensity=0.72, waypoint="hormuz"),
            SectorArc(source="RUS", target="IND", intensity=0.82),
            SectorArc(source="USA", target="DEU", intensity=0.7),
            SectorArc(source="SAU", target="DEU", intensity=0.55, waypoint="suez"),
        ],
        chokepoints=[CHOKEPOINTS["hormuz"], CHOKEPOINTS["suez"]],
        brief="Hydrocarbon geopolitics is fought at chokepoints. Route risk can hit inflation expectations before barrels disappear.",
        alpha="Track LNG, not only crude. Europe now imports energy security by ship, tying industry to Atlantic and Gulf routes.",
        equity_proxy="XLE / Brent crude",
    ),
    "critical-minerals": Sector(
        id="critical-minerals",
        name="Critical Minerals & EV Batteries",
        color="#2dff88",
        market_value="$200B batteries",
        systemic_multiplier="$2.8T+ autos and grid storage",
        sensitivity=9.5,
        power_nodes=["CHN", "BRA", "IND", "KOR", "JPN"],
        consumption_nodes=["DEU", "USA", "IND", "JPN", "KOR"],
        arcs=[
            SectorArc(source="BRA", target="CHN", intensity=0.74),
            SectorArc(source="CHN", target="DEU", intensity=0.92, waypoint="suez"),
            SectorArc(source="CHN", target="USA", intensity=0.86),
            SectorArc(source="CHN", target="IND", intensity=0.78, waypoint="malacca"),
            SectorArc(source="CHN", target="JPN", intensity=0.68),
            SectorArc(source="CHN", target="KOR", intensity=0.72),
        ],
        chokepoints=[CHOKEPOINTS["malacca"], CHOKEPOINTS["suez"]],
        brief="Battery supply chains look diversified at the mine but converge through processing. The bottleneck is sovereignty, not geology.",
        alpha="Indonesia is the swing read-through. If nickel policy tilts toward MSP partners, China's battery dominance gets its first structural challenge.",
        equity_proxy="LIT / REMX",
    ),
}
